print('hello world')
print('try your best')
print('to be intersting')
print('you are your own hero')
print("I'm not afraid to lose you, I am afraid to lose the faith that once I insisted on.")
print('just for test')
print('for test')
print('for ttttt')
